server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/pagamento?allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue